server.port=8081

spring.datasource.url=jdbc:h2:file:./data/expensedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
jwt.expiration=86400000
